export default {
  "reading-reimagined": {
    textColor: "black",
    desc: `Halotrade was a pilot build of an enterprise-grade supply chain application. I was the lead developer personally responsible for Infrastructure Planning, Full-Stack Development, and DevOps. This project not only challenged my macro strategizing while collaborating with the product manager, it was my first globally distributed application using Microsoft Azure. `,
    title: "Reading Reimagined",
    stack: ["AWS", "Terraform", "Typescript"],
    length: "short",
    sector: "EdTech",
    year: "2023",
    to: "/projects/reading-reimagined",
    architecture: {
      images: [
        { src: "progolf_architecture.jpg", alt: "Architecture Diagram" },
      ],
    },
  },
  aeyde: {
    textColor: "black",
    desc: `Halotrade was a pilot build of an enterprise-grade supply chain application. I was the lead developer personally responsible for Infrastructure Planning, Full-Stack Development, and DevOps. This project not only challenged my macro strategizing while collaborating with the product manager, it was my first globally distributed application using Microsoft Azure. `,
    title: "Aeyde",
    stack: ["AWS", "Shopify", "Node", "Typescript"],
    length: "short",
    sector: "Fashion",
    year: "2023",
    to: "/projects/aeyde",
    measurables: {},
    architecture: {
      images: [
        { src: "progolf_architecture.jpg", alt: "Architecture Diagram" },
      ],
    },
  },
  "progolf-berin": {
    textColor: "black",
    desc: `Halotrade was a pilot build of an enterprise-grade supply chain application. I was the lead developer personally responsible for Infrastructure Planning, Full-Stack Development, and DevOps. This project not only challenged my macro strategizing while collaborating with the product manager, it was my first globally distributed application using Microsoft Azure. `,
    title: "ProGolf Berlin",
    stack: ["Shopify", "Javascript", "CSS"],
    length: "short",
    sector: "Golf",
    year: "2022",
    to: "/projects/progolf-berin",
    measurables: {},
    architecture: {
      images: [
        { src: "progolf_architecture.jpg", alt: "Architecture Diagram" },
      ],
    },
  },
  "skin-kravings": {
    textColor: "black",
    desc: `Halotrade was a pilot build of an enterprise-grade supply chain application. I was the lead developer personally responsible for Infrastructure Planning, Full-Stack Development, and DevOps. This project not only challenged my macro strategizing while collaborating with the product manager, it was my first globally distributed application using Microsoft Azure. `,
    title: "Skin Kravings",
    stack: ["Shopify", "Javascript", "CSS"],
    length: "short",
    sector: "Beauty",
    year: "2022",
    to: "/projects/skin-kravings",
    liveLink: "https://cleyobeauty.com/",
  },
  halotrade: {
    textColor: "black",
    desc: `Halotrade was a pilot build of an enterprise-grade supply chain application. I was the lead developer personally responsible for Infrastructure Planning, Full-Stack Development, and DevOps. This project not only challenged my macro strategizing while collaborating with the product manager, it was my first globally distributed application using Microsoft Azure. `,
    title: "Halotrade",
    stack: ["Nuxt", "Azure", "Node", "NoSql"],
    length: "short",
    sector: "Finance",
    year: "2022",
    to: "/projects/halotrade",
  },
  emkfit: {
    textColor: "black",
    desc: `Implemented a full Shopify build for the talented fitness coach Emkfit. I was responsible for theme sourcing, store/configuration, liquid templating, testing, and deployment. I am still currently involved with ongoing required updates.`,
    title: "Emkfit",
    stack: ["Shopify", "HTML", "CSS", "JS"],
    length: "tall",
    sector: "Fitness",
    year: "2022",
    to: "/projects/emkfit",
    liveLink: "https://www.emkfit.ca",
  },
  "5oz": {
    textColor: "black",
    desc: `Provided Full-Stack refinements onto an existing cargo website. Included web and mobile responsiveness changes, and the addition of a Microsoft Azure hosted serverless newsletter sign up form.`,
    title: "5oz",
    stack: ["Cargo", "Azure", "CSS", "JS"],
    img: "5oz_prev.jpg",
    length: "short",
    sector: "Art",
    year: "2022",
    to: "/projects/5oz",
    liveLink: "https://www.5oz.com/",
  },
  spectral: {
    textColor: "black",
    desc: `A lightweight landing page build for a crypto company providing protocol for programmable creditworthiness. I implemented the provided figma design, ensuring responsiveness/accessibility, and added a functional newsletter form with a serverless backend.`,
    stack: ["HTML", "CSS", "JS", "Azure"],
    title: "Spectral",
    img: "spectral_prev.jpg",
    length: "tall",
    sector: "Crypto",
    year: "2021",
    to: "/projects/spectral",
    liveLink: "https://spectral.finance",
  },
  roam: {
    textColor: "black",
    desc: `An MVP android build of a security focused travel/document sharing application. I was the lead developer responsible for Infrastructure Planning, Full-Stack Development, and DevOps. Leveraging Google Firebase Authentication, Serverless Functions, and Storage, we were able to deploy a first build to testers. The app is still currently being tested.`,
    title: "Roam",
    stack: ["NsVue", "Android", "Firebase"],
    img: "roam_prev.jpg",
    length: "tall",
    sector: "Travel",
    year: "2021",
    to: "/projects/roam",
    liveLink:
      "https://play.google.com/store/apps/details?id=org.nativescript.roam&ah=a2IKKW6jUgH9cYUv2x3-Bc2J44I",
  },
  streamhub: {
    textColor: "black",
    desc: `My culminating project from the Le Wagon Full-Stack Development Boot Camp in Berlin. With a focus on intuitive UI (1-click login), and
a clean, refined design, the app consolidated all
of a users followed streamers from Twitch, Mixer,
and Youtube Gaming into one hub.
.`,
    title: "StreamHub",
    stack: ["Ruby", "Rails", "JS"],
    img: "streamHub_prev.jpg",
    length: "short",
    sector: "Video",
    year: "2020",
    to: "/projects/streamhub",
  },
};
